const FLEXIBLE_ROOT_CLASSNAME = "flexibleRoot"
const FLEXIBLE_COLUMN_CLASSNAME = "flexibleColumn"
const FLEXIBLE_GROUPBOX_CLASSNAME = "flexibleGroupBox"
const FLEXIBLE_GROUPBOX_CLASSNAME_LABEL = "flexibleGroupBoxLabel"
const FLEXIBLE_ACCENTED_GROUPBOX_CLASSNAME = "flexibleAccentedGroupBox"
const FLEXIBLE_ROW_CLASSNAME = "flexibleRow"
const FLEXIBLE_CELL_CLASSNAME = "flexibleCell"
const FLEXIBLE_LABELED_CLASSNAME = "flexibleLabeled"
const FLEXIBLE_LABELED_LABEL_CLASSNAME = "flexibleLabeledLabel"
const FLEXIBLE_LABELED_CHILD_CLASSNAME = "flexibleLabeledChild"
const INLINE_BUTTON_CLASSNAME = "inlineButton"
const INLINE_CHIP_CLASSNAME = "inlineChip"
const CLICKED_CLASSNAME = "pressedElement"
const ANCHORED_CLASSNAME = "anchored"

export {
  FLEXIBLE_ROOT_CLASSNAME,
  FLEXIBLE_COLUMN_CLASSNAME,
  FLEXIBLE_GROUPBOX_CLASSNAME,
  FLEXIBLE_GROUPBOX_CLASSNAME_LABEL,
  FLEXIBLE_ACCENTED_GROUPBOX_CLASSNAME,
  FLEXIBLE_ROW_CLASSNAME,
  FLEXIBLE_CELL_CLASSNAME,
  FLEXIBLE_LABELED_CLASSNAME,
  FLEXIBLE_LABELED_LABEL_CLASSNAME,
  FLEXIBLE_LABELED_CHILD_CLASSNAME,
  INLINE_BUTTON_CLASSNAME,
  INLINE_CHIP_CLASSNAME,
  CLICKED_CLASSNAME,
  ANCHORED_CLASSNAME
}
