const FLEXIBLE_COLUMN_CLASSNAME = "flexibleColumn"
const FLEXIBLE_ROW_CLASSNAME = "flexibleRow"
const FLEXIBLE_CELL_CLASSNAME = "flexibleCell"
const INLINE_BUTTON_CLASSNAME = "inlineButton"
const INLINE_CHIP_CLASSNAME = "inlineChip"
const CLICKED_CLASSNAME = "pressedElement"
const UNBOUNDED_CLASSNAME = "unbounded"

export {
  FLEXIBLE_COLUMN_CLASSNAME,
  FLEXIBLE_ROW_CLASSNAME,
  FLEXIBLE_CELL_CLASSNAME,
  INLINE_BUTTON_CLASSNAME,
  INLINE_CHIP_CLASSNAME,
  CLICKED_CLASSNAME,
  UNBOUNDED_CLASSNAME
}
